name: Read Google Sheet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  read_sheet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print date and time
        run: |
          date
          date -u
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install gspread google-auth

      - name: Run script
        env:
          GSHEET_KEY: ${{ secrets.GSHEET_KEY }}
        run: python read_sheets.py

      - name: Upload sheet_data.json
        uses: actions/upload-artifact@v3
        with:
          name: sheet-data
          path: sheet_data.json